
env:
  grid_x: 5
  grid_y: 5
  num_colors: 10
  default_color: 0
  default_obj: 0
  arc_local_actions: ["Translate", "Fill", "Rotate", "Flip"]
  arc_global_actions: ["Rotate", "Flip"]
  penalize_actions: ["Fill"]
  finish_reward: 10
  penality_reward: 1
  project_dir: "/home/bjlee/arc_trajectory_generator"
  train_paths: [
    "/home/bjlee/arc_exp/ICLR_DT/ARC_Data/diagonal_flip/train", 
    "/home/bjlee/arc_exp/ICLR_DT/ARC_Data/gravity/train", 
    "/home/bjlee/arc_exp/ICLR_DT/ARC_Data/stretch/train", 
    "/home/bjlee/arc_exp/ICLR_DT/ARC_Data/tetris/train"
    ]
  test_paths: [
    "/home/bjlee/arc_exp/ICLR_DT/ARC_Data/diagonal_flip/test",
    "/home/bjlee/arc_exp/ICLR_DT/ARC_Data/gravity/test",
    "/home/bjlee/arc_exp/ICLR_DT/ARC_Data/stretch/test",
    "/home/bjlee/arc_exp/ICLR_DT/ARC_Data/tetris/test"]

model:
  n_layer: 16
  n_head: 8
  n_embd: 256
  embd_pdrop: 0.1
  resid_pdrop: 0.1
  attn_pdrop: 0.1

seed: 0

train:
  total_timesteps: 1000000
  max_ep_len: 100
  learning_rate: 0.0005
  batch_size: 64
  save_cycle: 50
  weight_decay: 0.1
  beta1: 0.9
  beta2: 0.95
  tau: 0.005
  epsilon: 0.5
  dec_epsilon: 0.00001
  min_epsilon: 0.1
  gamma: 0.99
  gpu_num: 0

logging:
  logging_dir: "exps/"
  exp_type: "dqn"
  print_data: False
  use_tb: True
  log_interval: 1000
  num_evaluations: 20
